image: gazebo:libgazebo8

pipelines:
  default:
    - step:
        script:
          - apt update
          # Node 0.1
          - apt install -y curl
          - curl -sL https://deb.nodesource.com/setup_0.10 | bash -
          # Dependencies
          - apt install -y libjansson-dev nodejs libboost-dev imagemagick libtinyxml-dev mercurial cmake build-essential wget npm
          - npm install -g grunt
          # Install
          - ./deploy.sh
