image: gazebo:libgazebo8

pipelines:
  default:
    - step:
        script:
          - apt update
          # Node (xenial uses v4.6.2)
          - apt install -y nodejs
          # Dependencies
          - apt install -y libjansson-dev nodejs libboost-dev imagemagick libtinyxml-dev mercurial cmake build-essential wget
          - npm install -g grunt
          # Chrome
          - echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/chrome.list
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          - set -x && apt update && apt install -y xvfb google-chrome-stable
          - wget -q -O /usr/bin/xvfb-chrome https://bitbucket.org/atlassian/docker-node-chrome-firefox/raw/ff180e2f16ea8639d4ca4a3abb0017ee23c2836c/scripts/xvfb-chrome
          - ln -sf /usr/bin/xvfb-chrome /usr/bin/google-chrome
          - chmod 755 /usr/bin/google-chrome
          # Install
          - npm run deploy
          # Test
          - npm test
          - npm run coverage
          # Try update script
          - npm run update
          # Check docs can be generated
          - npm run docs
